"""add pdpa fields to user

Revision ID: 73ac1dd0b47d
Revises: 77d955f7f2f1
Create Date: 2026-03-26 02:27:28.271798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73ac1dd0b47d'
down_revision: Union[str, None] = '77d955f7f2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_logs_id', table_name='admin_logs')
    op.drop_table('admin_logs')
    op.add_column('users', sa.Column('pdpa_consented', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pdpa_accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pdpa_accepted_at')
    op.drop_column('users', 'pdpa_consented')
    op.create_table('admin_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='admin_logs_admin_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='admin_logs_pkey')
    )
    op.create_index('ix_admin_logs_id', 'admin_logs', ['id'], unique=False)
    # ### end Alembic commands ###
