"""remove unique from face

Revision ID: fa667a2475c9
Revises: 871b66fb91bd
Create Date: 2026-03-24 20:45:13.003347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "fa667a2475c9"
down_revision: Union[str, None] = "871b66fb91bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "face_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "embedding_vector", pgvector.sqlalchemy.Vector(dim=512), nullable=False
        ),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_face_embeddings_id"), "face_embeddings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_face_embeddings_user_id"), "face_embeddings", ["user_id"], unique=False
    )
    op.drop_index("ix_admin_logs_id", table_name="admin_logs")
    op.drop_table("admin_logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("admin_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("admin_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("target_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("target_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("detail", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
            name="admin_logs_admin_id_fkey",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="admin_logs_pkey"),
    )
    op.create_index("ix_admin_logs_id", "admin_logs", ["id"], unique=False)
    op.drop_index(op.f("ix_face_embeddings_user_id"), table_name="face_embeddings")
    op.drop_index(op.f("ix_face_embeddings_id"), table_name="face_embeddings")
    op.drop_table("face_embeddings")
    # ### end Alembic commands ###
